# Generated by Django 6.0 on 2026-02-27 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMorph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('morph_id', models.CharField(max_length=25)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('game_no', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=9)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'morph_id')},
            },
        ),
    ]
