# Generated by Django 6.1.1 on 2026-09-20 10:18

import django.db.models.deletion
import dracogate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMorph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=dracogate.models.vmorph_name_generator, max_length=32)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('game_no', models.PositiveSmallIntegerField()),
                ('unit', models.CharField()),
                ('init_options', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
