# Generated by Django 6.0.3 on 2026-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmorph',
            name='progress',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
