# Generated by Django 6.0 on 2026-03-05 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmorph',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
