# Generated by Django 6.0.3 on 2026-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmorph',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
    ]
