# Generated by Django 6.0 on 2026-02-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0002_alter_morph_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='morph',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
