# Generated by Django 6.0.3 on 2026-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0002_alter_virtualmorph_progress_delete_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmorph',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
