# Generated by Django 6.0 on 2026-02-15 03:05

import dracogate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0002_alter_morph_history_alter_morph_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='morph',
            name='options',
            field=models.JSONField(default=dict, validators=[dracogate.models.validate_options]),
        ),
    ]
