# Generated by Django 6.0 on 2026-02-15 03:05

import dracogate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0003_alter_morph_history_alter_morph_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='name',
            field=models.CharField(max_length=9, validators=[dracogate.models.validate_name]),
        ),
    ]
