# Generated by Django 6.0 on 2026-02-15 03:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0004_alter_morph_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='morph',
            unique_together={('user', 'morph_id')},
        ),
    ]
