# Generated by Django 6.0 on 2026-02-15 03:12

import dracogate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracogate', '0005_alter_morph_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='history',
            field=models.JSONField(default=list, validators=[dracogate.models.validate_history]),
        ),
    ]
